name: "Google Java Format"
description: "Automatically format Java files using Google Java Style"
author: "axel-op"
branding:
  color: "red"
  icon: "align-right"
inputs:
  args:
    description: "Arguments for the Google Java Format executable"
    required: false
    default: "--replace"
  files:
    description: "Pattern to match files to be formatted"
    required: false
    default: "**/*.java"
  skipCommit:
    description: "Set to true to not commit the changes"
    required: false
    default: "false"
runs:
  using: "node12"
  main: "index.js"
