name: Test

on: push

jobs:
  test:
    strategy:
      matrix:
        java-version: [8, 11]
        version: ["1.6", ""]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - uses: ./
        with:
          skipCommit: true
          version: ${{ matrix.version }}
